title: "Michael Allman" # your name (or website title) here
logo: "/images/Profile_picture_Circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>An Undergraduate</strong> in Geography and Environmental Science. 
  <br><br>
  Univeristy of Maryland, Baltimore County. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
