title: Michael Allman # your name (or website title) here
logo: "/images/Profile_picture_Circle.png?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A GES major at UMBC with a dual certificates in GIScience and Honors college. Planned graduation in 2022.  
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
