title: "Michael Allman" # your name (or website title) here

logo: "/images/Bio_pic_circle_no_backgorund.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an undergraduate in Geography and Environmental Science with a certificate in GIScience.
  <br><br>
  Univeristy of Maryland, Baltimore County. 
  <br><br>
  <a href="www.linkedin.com/in/michael-allman-147b82169/">View My LinkedIn Profile</a> 
  <br><br> 
theme: "jekyll-theme-minimal"
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
